---
title: "CloudComputing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CloudComputing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The workflow for using desertHydro on a cluster relies on a couple things.

#1 Proper R Installation

This vignette was built to operate on the Advanced Research Computing: [Monsoon](https://in.nau.edu/arc/overview/connecting-to-monsoon/ "Monsoon Page") 
@ Northern Arizona University.

After understanding the basics of the cluster. Create a bash script.

Example batch script
```
#!/bin/bash
#SBATCH --job-name=lazy                     # the name of your job
#SBATCH --output=/scratch/mmm683/lazy.txt    # this is the file your output and errors go to
#SBATCH --chdir=/scratch/mmm683            # your work directory
#SBATCH --time=02:00                        # (max time) 30 minutes, hmm ya that sounds good
#SBATCH --mem=600                          # (total mem) 4GB of memory hmm, sounds good to me
#SBATCH -c4                                 # 4 cpus, sounds good to me

module load workshop

# use 500MB of memory
#srun stress -m 1 --vm-bytes 500M --timeout 65s

# use 500MB of memory and 3 cpu threads
srun stress -c 3 -m 1 --vm-bytes 500M --timeout 65s

# the secret command
srun exercise4
```

```{r setup}
library(desertHydro)
```

